apiVersion: v1
kind: Service
metadata:
  name: devops-info-service
  namespace: default
  labels:
    app: devops-info-service
    tier: application
  annotations:
    description: "Service for DevOps Info Service application"

spec:
  type: NodePort

  selector:
    app: devops-info-service

  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080

  sessionAffinity: None

