apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-chart.fullname" . }}-headless
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "devops-chart.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    description: "Headless Service for StatefulSet DNS resolution"

spec:
  clusterIP: None

  selector:
    {{- include "devops-chart.selectorLabels" . | nindent 4 }}

  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}

