{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-chart.fullname" . }}-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "devops-chart.labels" . | nindent 4 }}
    type: application-secret
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.credentials }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

