apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "devops-chart.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    description: "Service for DevOps Info Service application"

spec:
  type: {{ .Values.service.type }}

  selector:
    {{- include "devops-chart.selectorLabels" . | nindent 4 }}

  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}

  sessionAffinity: None

